// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCcNYEMZncmWauoXZBBlXXXM2n_8LQy5g',
    appId: '1:214684299459:web:f4baedaf78dda6442c7276',
    messagingSenderId: '214684299459',
    projectId: 'signinsignup-project-acc66',
    authDomain: 'signinsignup-project-acc66.firebaseapp.com',
    storageBucket: 'signinsignup-project-acc66.firebasestorage.app',
    measurementId: 'G-YZ56ZQJ3VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSSJ6qqVFld4ql3MQvQ8MfNgClQYF6cAo',
    appId: '1:214684299459:android:e17e60fb7f8d9c592c7276',
    messagingSenderId: '214684299459',
    projectId: 'signinsignup-project-acc66',
    storageBucket: 'signinsignup-project-acc66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-d7odT8KAWrZqwAoXGyrH39LiGli1lyk',
    appId: '1:214684299459:ios:8311f21fd0cf203f2c7276',
    messagingSenderId: '214684299459',
    projectId: 'signinsignup-project-acc66',
    storageBucket: 'signinsignup-project-acc66.firebasestorage.app',
    iosBundleId: 'com.example.signinSignupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-d7odT8KAWrZqwAoXGyrH39LiGli1lyk',
    appId: '1:214684299459:ios:8311f21fd0cf203f2c7276',
    messagingSenderId: '214684299459',
    projectId: 'signinsignup-project-acc66',
    storageBucket: 'signinsignup-project-acc66.firebasestorage.app',
    iosBundleId: 'com.example.signinSignupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCcNYEMZncmWauoXZBBlXXXM2n_8LQy5g',
    appId: '1:214684299459:web:d6e28cdd4b9389e12c7276',
    messagingSenderId: '214684299459',
    projectId: 'signinsignup-project-acc66',
    authDomain: 'signinsignup-project-acc66.firebaseapp.com',
    storageBucket: 'signinsignup-project-acc66.firebasestorage.app',
    measurementId: 'G-T2M7BTYL8G',
  );
}
